### ISSUE TITLE
can not display the payload of event content obviously

### ISSUE THREAD

**Issue by dunty** [securekey/fabric-examples#7]
in the fun PrintChaincodeEvent of printer/blockprinter.go
pls add a line to display the string of event.Payload to display the event content obviouly.

like below:
```
p.Field("Payload", Base64URLEncode(event.Payload))
p.Field("Payload not Base64", string(event.Payload))
```

**Comment by bstasyszyn** [comment]
I'll be adding an update to fabric-cli that will allow more control over what fields are displayed in base64. Please look for an update within the next few days.

**Comment by dunty** [comment]
good job.
